apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-log
              mountPath: /var/log/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: mysql-log
          emptyDir: {}
