[template]
src   = "database_creds"
dest  = "/app/bin/database_creds"
owner = "root"
group = "root"
mode  = "0755"
keys = [
  "/openstack/database/credentials",
]
check_cmd = "/app/bin/check {{ .src }}"
