[template]
src   = "my.cnf"
dest  = "/etc/mysql/my.cnf"
owner = "root"
group = "root"
mode  = "0644"
keys = []
check_cmd = "/usr/sbin/mysqld --help > /dev/null"
#reload_cmd = "ps axu | grep '/usr/sbin/mysqld' | grep -v grep | awk '{ print $2 }'"
